### PR TITLE
Add version subcommand

### PR DESCRIPTION
**Pull request by dlsmith**

### CODE REVIEW

**Comment by algrs** [comment]
We don't actually need this; it's a feature that's automatically provided by `plumbum.cli`. In the `bin/s3` command, we set `VERSION` on the `Application`, which lets it automatically provide a `--version` option. In `bin/s3` we have:
```py
from baiji.package_version import __version__

class S3App(cli.Application):
    VERSION = __version__
```
which gives us
```
$ s3 --version
s3 2.5.0
```

Also, to add a subcommand, you need to both create the sub-`Application` and add it in `bin/s3`, with a line like
```py
S3App.subcommand("md5", "baiji.cli.MD5Command")
```

**Comment by dlsmith** [comment]
The subcommand is already declared: https://github.com/bodylabs/baiji/blob/master/bin/s3#L23

This is breaking a [command in `dev-tools`](https://github.com/bodylabs/dev-tools/blob/604df9a76f5ab19ab86ed64484c1251838ece63c/lib/s3.rb#L17), but I'm happy to change it to use `--version` if you prefer.

**Comment by algrs** [comment]
Hmm, must have missed that when I was copy-pasting to translate from the old commands.

I think we'd be better off switching to the more generally accepted `--version`... But then, I didn't intent this to be a breaking changeset....

**Comment by dlsmith** [comment]
So, I'm leaning towards keeping this as a temporary fix. Given the dev-tools auto update, and the number of places baiji is installed (cloned directly in some places, installed as a pinned dependency in others), it's going to be a lot more work to fix all the references so that the most recent version of baiji can be pulled down and made consistent with dev-tools. Are you ok with that?

**Comment by algrs** [comment]
Sure, sounds good -- how about merging this and opening the PR to remove it, so that we can have that hanging over us reminding us to remove it later?

**Comment by dlsmith** [comment]
Sure. Will do.

**Comment by dlsmith** [comment]
https://github.com/bodylabs/baiji/pull/29

**Comment by algrs** [comment]
👍 Looks like a plan, thank you!

**Pull request merged**
