### PR TITLE
Bug fix: persistent connection now cached correctly

### PR DESCRIPTION
**Pull request by lillekemiker**
@algrs You know the context here. I just need a second pair of eyes to merge.

For the sake of record keeping in PR:
The S3Connection class was never changing `self.connected` to `True` after establishing the connection to S3, so rather than reuse the cached connection, it kept creating new ones.
As a minor addition, `self._conn` was defined outside `__init__`. This is also fixed now.

### CODE REVIEW

**Comment by algrs** [comment]
:+1: Thanks for finding this @lillekemiker

**Comment by algrs** [comment]
:+1:

**Comment by paulmelnikow** [comment]
Whoa, nice! This seems kinda serious.

Could we add a test around the behavior, that the connection is reused? Maybe by mocking the connection, and asserting that two calls result in only a single call to the connection.

**Comment by lillekemiker** [comment]
@paulmelnikow - Argh!! You literally posted that as I was about to hit the new, shiny Squash Commit button on github...

**Comment by paulmelnikow** [comment]
Sorrrry!

**Comment by lillekemiker** [comment]
Added a unittest. @algrs & @paulmelnikow  Check and see if it's up to par. Maybe you want it in a different location or you  want the test done differently?
Let me know

**Comment by lillekemiker** [comment]
Hmm, looks like lint doesn't like that `test_s3.py` just crossed the 1000 lines-of-code mark. I guess that is kind of a lot. How would you like me to address this?

**Comment by algrs** [comment]
The tests are broken up into classes already, so it's probably a simple enough matter to split a few out into separate files.

**Comment by algrs** [comment]
Let me take a spin at it

**Comment by algrs** [comment]
@lillekemiker -- something like this. I also removed the lint disable line that would have caught this bug in the first place, and cleaned up the lint in the tests a bit.

**Comment by paulmelnikow** [comment]
👏

**Pull request merged**
